interactions:
- request:
    body: '{"biller_id": 2901, "account_number": "1111322016"}'
    headers:
      Accept: [application/vnd.regalii.v3.1+json]
      Accept-Encoding: ['gzip, deflate']
      Authorization: ['APIAuth 88879c1b066dc9aea6201f27be2bbba9:+TTf4cRhwxkSwXX4JlnGk/1ePY0=']
      Connection: [keep-alive]
      Content-Length: ['51']
      Content-MD5: [ZkNGR5IItPT5UO5fquuDpg==]
      Content-Type: [application/json]
      Date: ['Tue, 29 Jan 2019 17:26:20 GMT']
      User-Agent: [python-requests/2.20.1]
    method: POST
    uri: https://api.casiregalii.com/bills
  response:
    body: {string: '{"code":"R16","message":"Failed to make the consult, please try
        again later","id":8393}'}
    headers:
      Cache-Control: [no-cache]
      Connection: [keep-alive]
      Content-Type: [application/json; charset=utf-8]
      Date: ['Tue, 29 Jan 2019 17:26:21 GMT']
      Strict-Transport-Security: [max-age=31536000]
      Transfer-Encoding: [chunked]
      X-Content-Type-Options: [nosniff]
      X-Frame-Options: [SAMEORIGIN]
      X-Request-Id: [edc24444-4346-4fba-8a30-0c990eb8c019]
      X-Runtime: ['1.061626']
      X-XSS-Protection: [1; mode=block]
    status: {code: 422, message: Unprocessable Entity}
version: 1
