interactions:
- request:
    body: '{"biller_id": 2901, "account_number": "1111322016"}'
    headers:
      Accept: [application/vnd.regalii.v3.1+json]
      Accept-Encoding: ['gzip, deflate']
      Authorization: ['APIAuth 88879c1b066dc9aea6201f27be2bbba9:E8SDwqRnht3pWX6T8n0GnnpGBaM=']
      Connection: [keep-alive]
      Content-Length: ['51']
      Content-MD5: [ZkNGR5IItPT5UO5fquuDpg==]
      Content-Type: [application/json]
      Date: ['Wed, 16 Jan 2019 19:07:35 GMT']
      User-Agent: [python-requests/2.20.1]
    method: POST
    uri: https://api.casiregalii.com/bills
  response:
    body: {string: '{"code":"R16","message":"Failed to make the consult, please try
        again later","id":8393}'}
    headers:
      Cache-Control: [no-cache]
      Connection: [keep-alive]
      Content-Type: [application/json; charset=utf-8]
      Date: ['Wed, 16 Jan 2019 19:07:37 GMT']
      Strict-Transport-Security: [max-age=31536000]
      Transfer-Encoding: [chunked]
      X-Content-Type-Options: [nosniff]
      X-Frame-Options: [SAMEORIGIN]
      X-Request-Id: [4b26da33-e38c-4f16-84e3-4a5d9355025f]
      X-Runtime: ['1.053508']
      X-XSS-Protection: [1; mode=block]
    status: {code: 422, message: Unprocessable Entity}
version: 1
